### ISSUE TITLE
Colton Issues

### ISSUE THREAD

**Issue by coltonlloyd** [jclachance/BOFdat#10]
Get the following output when running setup.py. I tried to look into this and i'm not sure why this is.
```
Searching for cobra==0.8.0
Reading https://pypi.python.org/simple/cobra/
No local packages or working download links found for cobra==0.8.0
error: Could not find suitable distribution for Requirement.parse('cobra==0.8.0')
```
This could cause problems when users install the package from scratch (w/out cobrapy already installed)

**Comment by coltonlloyd** [comment]
`get_ratio` is called on line 202 of protein.py instead of `_get_ratio'

**Comment by coltonlloyd** [comment]
`in` is missing between `k,v` and `seq_dict.iteritems()`

**Comment by coltonlloyd** [comment]
I would create a .gitignore text file with the lines
`*.pyc`
and
`*.egg-info`
this will clean up your tracked changes on git

**Comment by coltonlloyd** [comment]
seaborn needs added to the setup.py required files

**Comment by jclachance** [comment]
Requirements.txt now requires cobra > 0.8, so pip should be able to find the latest version.

Although this may cause issues since cobra is not commited to an API yet.
