### ISSUE TITLE
Yara issues

### ISSUE THREAD

**Issue by yseif** [jclachance/BOFdat#11]
1. The current biomass function is updated. Sometimes, users will want to create a new biomass function. You could do that by just creating a new reaction with the same metabolites as that for the biomass function and subsequently change it. Otherwise, another cleaner way could be to just update the new biomass function with metabolites as each coefficient in computed.

Here's my way around it:
model = cobra.io.load_json_model(path_to_model)
model.reactions.iYS_BIOMASS2.objective_coefficient = 0
new_rx = Reaction('BOFdat_biomass')
model.add_reaction(new_rx)
new_rx.objective_coefficient = 1
new_rx.add_metabolites(model.reactions.iYS_BIOMASS2.metabolites)

2. You describe the units for the cell weight in femtograms, however my organism's weight is measured in milligrams which amounts to a difference of 12 orders of magnitude. It would be great that you specify if that would affect subsequent calculations.

3. Sometimes, users do not have access to proteomics datasets. And even if their organism is well studied, these datasets are not readily available online. At the most, partial datasets are published in literature. It would be great that you determined a lower threshold for the number of quantitatively measured protein counts.

4. When passing a csv file with locus tags instead of protein IDs. for the  BOFdat.protein.generate_coefficients command, python spits out an error without describing the source of the error.

5. When passing a .csv file with columns ['relative_abundance', 'locus_tag'], another error pops up which is resolved when the order of the columns is switched back.

**Comment by jclachance** [comment]
1. In the case of a new biomass, users can collect the dictionaries and use it directly to generate a biomass. The case currently used in BOFdat is more general and may fit more user needs.

2. Cell weight was cancelled in the calculation so is now removed from the potential user inputs.

3. Indeed. We would argue that some data is better than no data as further datasets may come and improve the existing ones.

4. Error message has been added.

5. The order of the columns do not matter anymore.
