### ISSUE TITLE
Yara issues - part 2

### ISSUE THREAD

**Issue by yseif** [jclachance/BOFdat#12]
1. The following description is given in two different functions; the metabolite and the lipids function.
"path_to_conversion_file – a dictionary converting from the name present in the lipidomic data to BiGG identifiers. This dictionary is generated through manual curation from the modeller. "

2. Why not ask the user to pass a dataframe directly to the function "BOFdat.lipid.generate_coefficients" instead of passing a dictionary to "BOFdat.lipid.filter_for_model_lipid" and then the dataframe that comes out of it to "BOFdat.lipid.generate_coefficients"

3. I think you want to change a dictionary to path to file containing, "path_to_conversion_file – a dictionary converting from the name present in the lipidomic data to BiGG identifiers. This dictionary is generated through manual curation from the modeller."

4. Passed a path to file containing a pickle dictionary and got this error message:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-28-3997da197e21> in <module>()
     10 pickle.dump(conversion_file, open('/home/yara/Documents/UO1/Intermediate/Reconstruction/BOFdat/lipids_conversion.p', 'w'))
     11 path_to_conversion_file = '/home/yara/Documents/UO1/Intermediate/Reconstruction/BOFdat/lipids_conversion.p'
---> 12 BOFdat.lipid.filter_for_model_lipid(path_to_conversion_file, path_to_model)

/usr/local/lib/python2.7/dist-packages/BOFdat-0.1.0-py2.7.egg/BOFdat/lipid.pyc in filter_for_model_lipid(path_to_conversion_file, path_to_model)
     36     to_bigg_df = pd.read_csv(path_to_conversion_file)
     37     to_bigg_dict = dict(zip([i for i in to_bigg_df[to_bigg_df.columns[0]]],
---> 38                             [i for i in to_bigg_df[to_bigg_df.columns[1]]]))
     39 
     40     # Get the metabolites that are in the model

/usr/local/lib/python2.7/dist-packages/pandas/indexes/base.pyc in __getitem__(self, key)
   1262 
   1263         if lib.isscalar(key):
-> 1264             return getitem(key)
   1265 
   1266         if isinstance(key, slice):

IndexError: index 1 is out of bounds for axis 0 with size 1

5. Explain what the "BOFdat.lipid.filter_for_model_lipid" exactly does.

**Comment by jclachance** [comment]
1. 2. 3. 4.The new version of BOFdat has replaced the name of the input "to_bigg_dict" which was confusing with "path_to_conversion_file" which is a .csv file.

5.Finds lipids identified through manual curation in model. (added to docstring)
