### ISSUE TITLE
Error when parsing RNA features in genbank files 

### ISSUE THREAD

**Issue by EBosi** [jclachance/BOFdat#18]
The function `bd.rna.generate_coefficients` gives an error for my genbank file. The error is the following:

``` python
rna_coefficients = bd.rna.generate_coefficients(genbank,model,transcriptomic,RNA_WEIGHT_FRACTION=rna_weight_fraction)

rna_coefficients

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-12-be0e13c58858> in <module>()
----> 1 rna_coefficients = bd.rna.generate_coefficients(genbank,model,transcriptomic,RNA_WEIGHT_FRACTION=rna_weight_fraction)
      2 rna_coefficients

/hdd/FNN_recon/BOFdat/BOFdat/rna.pyc in generate_coefficients(path_to_genbank, path_to_model, path_to_transcriptomic, RNA_WEIGHT_FRACTION, rRNA_WEIGHT_FRACTION, tRNA_WEIGHT_FRACTION, mRNA_WEIGHT_FRACTION, identifier)
    289     # Operations
    290     model = _import_model(path_to_model)
--> 291     rRNA_dict, tRNA_dict, mRNA_dict = _process_record(path_to_genbank,path_to_transcriptomic,identifier)
    292     RNA_coefficients = _total_coefficients(rRNA_dict, tRNA_dict, mRNA_dict,
    293                                            mRNA_WEIGHT_FRACTION, tRNA_WEIGHT_FRACTION, rRNA_WEIGHT_FRACTION)

/hdd/FNN_recon/BOFdat/BOFdat/rna.pyc in _process_record(path_to_genbank, path_to_transcriptomic, identifier)
    174                     rna_seq = _get_RNA_sequence(element.location, element.strand, record)
    175                     tRNA_seq.append(rna_seq)
--> 176                     tRNA_locus.append(element.qualifiers['locus_tag'][0])
    177                     tRNA_number.append(_get_number(rna_seq))
    178 

KeyError: 'locus_tag'
```
In my case, the tRNA and rRNA features lack the locus_tag field in the genbank file... however this is not necessarily bad! According to NCBI's Prokaryotic Genome Annotation Guide (https://www.ncbi.nlm.nih.gov/genbank/genomesubmit_annotation/#RNA):

> RNA features (rRNA, tRNA, ncRNA) must include a corresponding gene feature with a locus_tag qualifier. Please be sure to specify which amino acid the tRNA gene corresponds to. If the amino acid of a tRNA is unknown, use tRNA-Xxx as the product, as in the example. Many submitters like to label the tRNAs such as tRNA-Gly1, etc. If you wish to do this please include "tRNA-Gly1" as a note and not in /gene. The use of /gene is reserved for the actual biological gene symbol such as "trnG". If a tRNA is a pseudogene, please use the /pseudo qualifier.
Annotate ncRNAs that belong to one of the INSDC ncRNA_class as an ncRNA feature, with the appropriate value in the required /ncRNA_class qualifier. Regions of an RNA should be annotated as a misc_feature (eg, leader sequences), or a misc_binding feature if they bind a known molecule (eg, riboswitches). See Other Annotation for examples of regions of RNAs.

I'm fixing this and making a pull request

**Comment by jclachance** [comment]
I have just accepted your pull request. Thank you very much for the contribution.
