### ISSUE TITLE
Small technicalities

### ISSUE THREAD

**Issue by yseif** [jclachance/BOFdat#2]
1 - What do you mean by "metabolites" when you say macromolecules supported?
2 - Organism GenBank annotation, format = genbank, .gb,.gbff (any format supported by BioPython) -> you'll probably run into some issues with that. You should be more specific because sometimes the feature.qualifiers will pull out different keys.

**Comment by jclachance** [comment]
I will address those soon. Thx.

**Comment by jclachance** [comment]
The new documentation should solve these issues.
