### ISSUE TITLE
Error when uploading transcriptomic data

### ISSUE THREAD

**Issue by Christiansj83** [jclachance/BOFdat#27]
During handling of the above exception, another exception occurred:

    Exception                                 Traceback (most recent call last)

    <ipython-input-5-1680785b6bb2> in <module>()
    ----> 1 rna_coefficients = step1.generate_rna_coefficients(genbank_D39_transcriptomics,model,transcriptomic,RNA_WEIGHT_FRACTION=rna_weight_fraction, identifier='locus_tag')
          2 rna_coefficients

    ~/.local/lib/python3.6/site-packages/BOFdat-0.1.6-py3.6.egg/BOFdat/step1.py in generate_rna_coefficients(path_to_genbank, path_to_model, path_to_transcriptomic, RNA_WEIGHT_FRACTION, rRNA_WEIGHT_FRACTION, tRNA_WEIGHT_FRACTION, mRNA_WEIGHT_FRACTION, identifier)
         66                          tRNA_WEIGHT_FRACTION,
         67                          mRNA_WEIGHT_FRACTION,
    ---> 68                          identifier)
         69 
         70     return rna_coefficients

    ~/.local/lib/python3.6/site-packages/BOFdat-0.1.6-py3.6.egg/BOFdat/core/rna.py in generate_coefficients(path_to_genbank, path_to_model, path_to_transcriptomic, RNA_WEIGHT_FRACTION, rRNA_WEIGHT_FRACTION, tRNA_WEIGHT_FRACTION, mRNA_WEIGHT_FRACTION, identifier)
        321         rRNA_dict, tRNA_dict, mRNA_dict = _process_record(path_to_genbank,path_to_transcriptomic,identifier)
        322     except:
    --> 323         raise Exception('Could not distinguish mRNA, tRNA and rRNA from file')
        324     RNA_coefficients = _total_coefficients(rRNA_dict, tRNA_dict, mRNA_dict,
        325                                            mRNA_WEIGHT_FRACTION, tRNA_WEIGHT_FRACTION, rRNA_WEIGHT_FRACTION)

    Exception: Could not distinguish mRNA, tRNA and rRNA from file

**Comment by jclachance** [comment]
The issue arose from the transcriptomic file being wrong, not comma-separated and 3 columns. 

The high-level try/except was remove to allow for a more specific error message that can better guide users troubleshoot the issue on their own.
