### ISSUE TITLE
Python3 compatibility issue in protein.py

### ISSUE THREAD

**Issue by Christiansj83** [jclachance/BOFdat#28]
82     # Values = the occurence of that amino acid
         83     list_of_dict = []
    ---> 84     for k,v in seq_dict.iteritems():
         85         list_of_occurences = []
         86         # Get the occurence for each letter

    AttributeError: 'dict' object has no attribute 'iteritems

**Comment by jclachance** [comment]
Christian, can you verify if you still get the error?

In terminal:
git clone https://github.com/jclachance/BOFdat.git

and in the repository where you cloned it 
cd BOFdat
ls
(you should see a setup.py file)
python3 setup.py install --user

Then run again and make sure your proteomic file is comma-separated.

**Comment by Christiansj83** [comment]
Hi JC. 
It is still not working. I get the same error:
     82     # Values = the occurence of that amino acid
     83     list_of_dict = []
---> 84     for k,v in seq_dict.iteritems():
     85         list_of_occurences = []
     86         # Get the occurence for each letter

**Comment by Christiansj83** [comment]
Now it works!
