### ISSUE TITLE
Error with model reading

### ISSUE THREAD

**Issue by franciscozorrilla** [jclachance/BOFdat#32]
Hi JC,

I am running into some errors when reading in a model I generated from homology using the RAVEN toolbox. More specifically, when I run:

```
pip install BOFdat
python

from BOFdat import step1
from BOFdat.util import update
import pandas as pd
import cobra

dna_weight_fraction = 0.03
rna_weight_fraction = 0.1
protein_weight_fraction = 0.5
lipid_weight_fraction = 0.07
metabolite_weight_fraction = 0.3

genome = '/c3se/users/zorrilla/Vera/BOFdat/hpo.fna'
genbank = '/c3se/users/zorrilla/Vera/BOFdat/hpo.gbff'
model = '/c3se/users/zorrilla/Vera/BOFdat/modelHpoHomology.xml'

dna_coefficients=step1.generate_dna_coefficients(genome,model,DNA_WEIGHT_FRACTION=dna_weight_fraction)
```

I get the following errors:

```
Traceback (most recent call last):
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/cobra/io/sbml3.py", line 587, in read_sbml_model
    return parse_xml_into_model(xml, number=number)
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/cobra/io/sbml3.py", line 384, in parse_xml_into_model
    rxn_id = clip(get_attrib(sbml_objective, "fbc:reaction"), "R_")
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/cobra/io/sbml3.py", line 169, in clip
    return string[len(prefix):] if string.startswith(prefix) else string
AttributeError: NoneType object has no attribute startswith

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/BOFdat/step1.py", line 30, in generate_dna_coefficients
    dna_coefficients = dna.generate_coefficients(path_to_fasta, path_to_model , DNA_WEIGHT_FRACTION=0.031)
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/BOFdat/core/dna.py", line 107, in generate_coefficients
    model = _import_model(path_to_model)
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/BOFdat/core/dna.py", line 29, in _import_model
    return cobra.io.read_sbml_model(path_to_model)
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/cobra/io/sbml3.py", line 590, in read_sbml_model
    "Something went wrong reading the model. You can get a detailed "
cobra.io.sbml3.CobraSBMLError: Something went wrong reading the model. You can get a detailed report using the `cobra.io.sbml3.validate_sbml_model` function or using the online validator at http://sbml.org/validator

```

I ran the model through the SMBL validator and it seems to be due to some chemical formula names, so I tried some manual curation.

Before manual curation of metabolites:

![image](https://user-images.githubusercontent.com/35606471/55892083-f50d2b80-5bb5-11e9-81be-84a02d74c745.png)

After manual curation of metabolites:

![image](https://user-images.githubusercontent.com/35606471/55892045-e6267900-5bb5-11e9-8292-6576a5d7db08.png)

Is it possible to bypass this error and just throw a warning?
Or could I fix these issues simply by setting a particular version of SMBL when exporting my model from MATLAB?
Do you have any other suggestions?

Thanks and Best wishes,
Francisco

**Comment by jclachance** [comment]
Hi Francisco,

As you pointed out it seems to be an error with the generated sbml format that comes out of matlab. 

A quick workaround that is worth a try would be (if available) to save your model in json format and provide this model to BOFdat. 

Thank you,

JC

**Comment by franciscozorrilla** [comment]
Hey JC,

Yep, I managed to fix by using a newer model version + getting the latest RAVEN version.

However, I am now getting the following errors:

```
dna_coefficients=step1.generate_dna_coefficients(genome,model,DNA_WEIGHT_FRACTION=dna_weight_fraction)
/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/BOFdat/core/dna.py:17 UserWarning: 7 handles in the genome file.This may indicate that your genome is not completely assembled.
BOFdat will parse the contigs but the stoichiometric coefficients may not be accurate.
Traceback (most recent call last):
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/cobra/core/dictlist.py", line 451, in __getattr__
    return DictList.get_by_id(self, attr)
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/cobra/core/dictlist.py", line 58, in get_by_id
    return list.__getitem__(self, self._dict[id])
KeyError: 'datp_c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/BOFdat/step1.py", line 30, in generate_dna_coefficients
    dna_coefficients = dna.generate_coefficients(path_to_fasta, path_to_model , DNA_WEIGHT_FRACTION=0.031)
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/BOFdat/core/dna.py", line 109, in generate_coefficients
    DNA_WEIGHT_FRACTION)
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/BOFdat/core/dna.py", line 73, in _convert_to_coefficient
    base_to_bigg = {'A': model.metabolites.datp_c, 'T': model.metabolites.dttp_c,
  File "/c3se/users/zorrilla/Vera/.conda/envs/snakemake_env/lib/python3.6/site-packages/cobra/core/dictlist.py", line 454, in __getattr__
    attr)
AttributeError: DictList has no attribute or entry datp_c

```

Any tips on how to solve this?
Is this due to the fact that my genome file contains 7 handles, or is this an unrelated warning?
I tried updating my BOFdat and cobra packages, but still get the same errors!

Thanks,
Francisco

**Comment by jclachance** [comment]
Hi Francisco,

Indeed, as of now, BOFdat only support BiGG IDs. Emanuel Bosi did suggest that we implement a workaround for other identifiers by hardcoding it in BOFdat, at least for step1. 
Are the identifiers for yeast-GEM specific to the model or are they in a format compatible with MetaNetX?

JC

**Comment by EBosi** [comment]
Hi,
Francisco, I've added this feature to BOFdat, it works for me (seed ids). Briefly, you should provide some conversion tables in which you specify the correspondent metabolites of the bigg ids used in bofdat.
I think I've sent JC my version, I could also share (fork, push) my version on monday... let me know if I can help!
Best,
Emanuele

**Comment by jclachance** [comment]
Hi,

Thanks for the prompt reply Emanuele. Yes, I think doing a pull request to the main repo of BOFdat would be the best way. Let me know if there are permission issues. 

JC

**Comment by franciscozorrilla** [comment]
@jclachance I see! I am not sure if the metabolite IDs of yeast GEM are specific to the model or if they follow some standard format, however I know that the metabolites are at least annotated with ChEBI, SBO, and kegg compound IDs. I think these are compatible with MetaNetX?

@EBosi Great! Please let me know how I can access your version of BOFdat. Grazie mille.

**Comment by EBosi** [comment]
I pushed the changes in my fork and asked @jclachance for a merge... please read the referenced issue and comment if you need.

**Comment by franciscozorrilla** [comment]
OK I have obtained the latest version of BOFdat (from JC) and manually generated my conversion tables to match what I have in my model.

Next I tried running the following:

```
>>> from BOFdat import step1
>>> from BOFdat.util import update
>>> import pandas as pd
>>> import cobra
>>> dna_weight_fraction = 0.03
>>> rna_weight_fraction = 0.1
>>> protein_weight_fraction = 0.5
>>> lipid_weight_fraction = 0.07
>>> metabolite_weight_fraction = 0.3
>>>
>>> genome = '/c3se/users/zorrilla/Vera/BOFdat/hpo.fna'
>>> genbank = '/c3se/users/zorrilla/Vera/BOFdat/hpo.gbff'
>>> model = '/c3se/users/zorrilla/Vera/BOFdat/modelHpoHomology.xml'
>>> dnaTable='/c3se/users/zorrilla/Vera/temp/BOFdat/dntps.conversion_table.txt'
>>> dna_coefficients=step1.generate_dna_coefficients(genome,model,DNA_WEIGHT_FRACTION=dna_weight_fraction,conversion_table=dnaTable)
```
Which generates the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/c3se/users/zorrilla/Vera/.conda/envs/concoct_env/lib/python2.7/site-packages/BOFdat-0.1.7-py2.7.egg/BOFdat/step1.py", line 30, in generate_dna_coefficients
    dna_coefficients = dna.generate_coefficients(path_to_fasta, path_to_model , DNA_WEIGHT_FRACTION=0.031, conversion_table=conversion_table)
TypeError: generate_coefficients() got an unexpected keyword argument 'conversion_table'
```


Here is a zip file containing the dna fasta, genbank file, model, and dntp conversion table:

[BOFerror.zip](https://github.com/jclachance/BOFdat/files/3142918/BOFerror.zip)

Any idea what could be going wrong?
Is BOFdat not recognizing my conversion table?

Thanks,
Francisco

**Comment by jclachance** [comment]
Yeah that makes sense since the conversion table argument is present in the step1 function call but not in the actual function. 

I think converting all necessary metabolite ID and then passing to the functions generating the coefficients may be a better way to go here.

**Comment by franciscozorrilla** [comment]
@jclachance Thanks for the advice! 
I manually changed metabolite IDs using a similar approach to @EBosi:

```
while read line ;do 
   BIGG=$(echo "$line"|cut -f 1);
   MODEL=$(echo "$line"|cut -f 2); 
   sed -i "s/$MODEL/$BIGG/g" modelHpoMerged.xml;
done < model2bigg.txt
```

where model2bigg.txt contains the following:

```
ala__L_c	M_s_0955
cys__L_c	M_s_0981
asp__L_c	M_s_0973
glu__L_c	M_s_0991
phe__L_c	M_s_1032
gly_c	M_s_1003
his__L_c	M_s_1006
ile__L_c	M_s_1016
lys__L_c	M_s_1025
leu__L_c	M_s_1021
met__L_c	M_s_1029
asn__L_c	M_s_0969
pro__L_c	M_s_1035
gln__L_c	M_s_0999
arg__L_c	M_s_0965
ser__L_c	M_s_1039
thr__L_c	M_s_1045
val__L_c	M_s_1056
trp__L_c	M_s_1048
tyr__L_c	M_s_1051
atp_c	M_s_0434
ctp_c	M_s_0539
gtp_c	M_s_0785
dttp_c	M_s_0650
datp_c	M_s_0586
dctp_c	M_s_0590
dgtp_c	M_s_0617
ppi_c	M_s_1322
```

Now the metabolite IDs look like this: 

`<species metaid="ala__L_c" sboTerm="SBO:0000247" id="ala__L_c" name="L-alanine" compartment="c" initialConcentration="0" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false" fbc:charge="0" fbc:chemicalFormula="C3H7NO2">`

However, I get the following errors when I try running step 1:
```
>>> from BOFdat import step1
>>> from BOFdat.util import update
>>> import pandas as pd
>>> import cobra
>>>
>>> dna_weight_fraction = 0.03
>>> rna_weight_fraction = 0.1
>>> protein_weight_fraction = 0.5
>>> lipid_weight_fraction = 0.07
>>> metabolite_weight_fraction = 0.3
>>>
>>> genome = '/c3se/users/zorrilla/Vera/temp/BOFdat/hpo.fna'
>>> genbank = '/c3se/users/zorrilla/Vera/temp/BOFdat/hpo.gbff'
>>> model = '/c3se/users/zorrilla/Vera/temp/BOFdat/modelHpoHomology.xml'
>>>
>>> dna_coefficients=step1.generate_dna_coefficients(genome,model,DNA_WEIGHT_FRACTION=dna_weight_fraction)
/c3se/users/zorrilla/Vera/.conda/envs/concoct_env/lib/python2.7/site-packages/BOFdat-0.1.7-py2.7.egg/BOFdat/core/dna.py:19 UserWarning: 7 handles in the genome file.This may indicate that your genome is not completely assembled.
BOFdat will parse the contigs but the stoichiometric coefficients may not be accurate.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/c3se/users/zorrilla/Vera/.conda/envs/concoct_env/lib/python2.7/site-packages/BOFdat-0.1.7-py2.7.egg/BOFdat/step1.py", line 37, in generate_dna_coefficients
    DNA_WEIGHT_FRACTION=0.031)
  File "/c3se/users/zorrilla/Vera/.conda/envs/concoct_env/lib/python2.7/site-packages/BOFdat-0.1.7-py2.7.egg/BOFdat/core/dna.py", line 113, in generate_coefficients
    model = _import_model(path_to_model)
  File "/c3se/users/zorrilla/Vera/.conda/envs/concoct_env/lib/python2.7/site-packages/BOFdat-0.1.7-py2.7.egg/BOFdat/core/dna.py", line 31, in _import_model
    return cobra.io.read_sbml_model(path_to_model)
  File "/c3se/users/zorrilla/Vera/.conda/envs/concoct_env/lib/python2.7/site-packages/cobra/io/sbml3.py", line 572, in read_sbml_model
    xmlfile = parse_stream(filename)
  File "/c3se/users/zorrilla/Vera/.conda/envs/concoct_env/lib/python2.7/site-packages/cobra/io/sbml3.py", line 156, in parse_stream
    return parse(filename)
  File "src/lxml/etree.pyx", line 3424, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
IOError: Error reading file '/c3se/users/zorrilla/Vera/temp/BOFdat/modelHpoHomology.xml': failed to load external entity "/c3se/users/zorrilla/Vera/temp/BOFdat/modelHpoHomology.xml"

```

Did my sed command mess up the model file somehow?

I just ran the model file (and the model before making the name changes) through the SMBL validator and it seems to be fine. I also loaded the model back into RAVEN/MATLAB  after making the metabolite ID changes and it seems to be fine. Heres the model in case you wanna take a look:


[modelHpoBIGG.zip](https://github.com/jclachance/BOFdat/files/3169146/modelHpoBIGG.zip)


Any clues what could be going wrong?

Thanks for the help,
Francisco

**Comment by jclachance** [comment]
Hi Francisco,

I can generate DNA coefficients with BOFdat using the model you sent. 

You may want to consider:
1- Upgrading cobra, which in turn may upgrade -->
2- The xml parser (lxml in your case)

Can you provide me the current versions of COBRA/libxml you are using? It seems like upgrading the requirements for BOFdat might be necessary.

Also, are your identifiers custom or are they SEED? I have an idea for the conversion of metabolite IDs that may simplify what was previously suggested by @EBosi. 

Cheers,

JC

**Comment by franciscozorrilla** [comment]
Hey JC, 

I upgraded cobra and lxml and now it works, thank you!
Here are the old versions that dont work:

```
cobra                     0.14.2                    <pip>
lxml                      4.3.1                     <pip>
```

I am unsure where they came from but they are not SEED to the best of my knowledge.
If you would like to know more details I can ask my colleagues and get back to you.
Please let me know more about your idea.

Best,
Francisco
