### ISSUE TITLE
BOF without any experimental data

### ISSUE THREAD

**Issue by franciscozorrilla** [jclachance/BOFdat#34]
Hey JC,

This is more of a question than an issue. If I understand correctly, the following steps absolutely require experimental data: 

```

rna_coefficients = step1.generate_rna_coefficients(genbank,model,transcriptomic,RNA_WEIGHT_FRACTION=rna_weight_fraction)
lipid_coefficients = step1.generate_lipid_coefficients(lipidomic_abundances,lipidomic_conversion,model,LIPID_WEIGHT_FRACTION=lipid_weight_fraction)
protein_coefficients = step1.generate_protein_coefficients(genbank,model,proteomic,PROTEIN_WEIGHT_FRACTION=protein_weight_fraction)
maintenance_cost = step1.generate_maintenance_costs(maintenance,model)

```

I am wondering if it is possible, or if it would even be useful to have an option to generate the BOF solely based on the model, genbank, protein fasta, and dna fasta? i.e. without any experimental data? 

I can elaborate a bit on my purposes: I want to use a homology-based approach to reconstruct a GEM. Essentially I use an existing well curated model as a template to create a draft model for a closely related organism. Ideally I would want to create a new BOF for this closely related organism, or at least make significant modifications to the template's BOF to match the new model. Perhaps BOFdat could take my template model with well curated BOF coefficients as an input to use for the coefficients where I dont have experimental data to provide? My goal is to create a working model, which can later have its BOF coefficients refined with experimental data.

Let me know what you think.
Best,
Francisco

**Comment by jclachance** [comment]
I realize I never replied to this, sorry!

It is totally possible. What you can do is simply generate a "dummy" experimental data where the weight of each gene, let's say in proteomic, is equal to a constant, i.e.: b0001, 1; b0002, 2; ...

In this case you should be able to generate stoichiometric coefficients that should not be too far off if your macromolecular weight fraction is reasonable. There is a supplementary figure in the paper that shows that (Fig. S7).

Sorry again for the very late reply,

JC

**Comment by Shakra-A** [comment]
Hello, I understood the dummy data for abundance files. I want to ask about the maintenance file. how to make dummy for that?
